services:
  scraper:
    build: .
    environment:
      - URL=${URL}
      - S3_URL=${S3_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
